check if the regex search is None before group, avoid NoneType error
Solves this error when using a single genotype text file instead of genotypes separated by chromomsome

line 52, in sort_geno
    x_ = chr_.search(x).group(1)
AttributeError: 'NoneType' object has no attribute 'group'